sudo: false
dist: bionic
language: node_js
node_js:
  - '12'
services:
  - xvfb
addons:
  firefox: latest
  chrome: latest
cache:
  directories:
    - node_modules
notifications:
  email: none
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
  - npm run coverage:upload
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
